export const ADD_TODO = 'ADD_TODO';
export const SHOW_OR_HIDE_MODAL_BUTTON_CLICKED = 'SHOW_OR_HIDE_MODAL_BUTTON_CLICKED';
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const CLOSE_CREATE_TODO_MODAL = 'CLOSE_CREATE_TODO_MODAL'